### PR TITLE
add minimal Lar TPC example

### PR DESCRIPTION
**Pull request by hanswenzel**
adding gdml  and fcl files to run minimal LArTPC example as described in the last larsoft coordination meeting

### CODE REVIEW

**Comment by knoepfel** [comment]
Hans, because this depends on utilities from larsim, could you please move this to the larsim repository?  We would like it to go in a top-level `larsim/example` subdirectory.

**Comment by hanswenzel** [comment]
Hi Kyle

I created the wenzel_larsim_develop<https://github.com/hanswenzel/larsim/tree/wenzel_larsim_develop>
branch on

https://github.com/hanswenzel/larsim

On branch wenzel_larsim_develop
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

modified:   CMakeLists.txt
new file:   example/CMakeLists.txt
new file:   example/MinimalLArTPCdetector.gdml
new file:   example/MinimalLArTPCdetector_g4.gdml
new file:   example/MinimalLArTPCdetector_g4_nowires.gdml
new file:   example/MinimalLArTPCdetector_nowires.gdml
new file:   example/test_MinimalLArTPC.fcl



 have a look and see if that's the way you want it



cheers Hans


--

Dr. Hans Wenzel



Physics and Detector Simulation

Fermi National Accelerator Laboratory

P.O. Box 500, MS 223

Batavia, Illinois 60510

USA



630 840 6034 office

331 250 9342  mobile

home.fnal.gov/~wenzel<http://home.fnal.gov/~wenzel>

wenzel@fnal.gov<mailto:wenzel@fnal.gov>

________________________________

**Comment by knoepfel** [comment]
Thanks @hanswenzel; we'll take a look.

**Comment by knoepfel** [comment]
@hanswenzel, the feature branch in larsim looks good.  Can you close this PR, and open one in larsim with the changes?

**Pull request closed without merging**
