### PR TITLE
Using the MCParticle method to keep transportation steps, with configurable parameter in ParticleListAction

### PR DESCRIPTION
**Pull request by calcuttj**

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
CI tests are normal for the experiments that are updated to use the latest larsoft.

**Comment by absolution1** [comment]
approved

**Comment by calcuttj** [comment]
Thank you all for the help

**Comment by lgarren** [comment]
approve

**Pull request merged**
