### PR TITLE
fix missing traj. endpoints and add filter for primary process

### PR DESCRIPTION
**Pull request by drivera-fnal**

### CODE REVIEW

**Comment by aihimmel** [comment]
Looks fine to me.
-Alex

On Apr 30, 2020, at 7:26 PM, Fermilab build bot account <notifications@github.com> wrote:

﻿

+code-checks
for details see
https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//527/console

**Comment by yangtj207** [comment]
trigger build

**Comment by lgarren** [comment]
@aihimmel If you mean to signal level 2 approval, would you please type "approve".   Thanks
Instructions: https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions

**Comment by ghost** [comment]
The corresponding DUNE CI test reports a 10% increase in memory usage for g4 protoDUNE-SP, this is probably expected. However, there is also a tiny change of one hit (out of 58 811 hits) in reco protoDUNE-SP. Do we understand how the code changes in this larg4 pull request can affect the protoDUNE-SP reco products?

Here is the link to the DUNE CI test: [https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/8847&platform=Linux%203.10.0-1062.12.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof](url)

**Comment by aihimmel** [comment]
Maybe I’m confused then. Wasn’t this intended to reduce G4 memory?
-Alex

On May 2, 2020, at 6:17 AM, Christoph Alt <notifications@github.com> wrote:

﻿

The corresponding DUNE CI test reports a 10% increase in memory usage for g4 protoDUNE-SP, this is probably expected. However, there is also a tiny change of one hit (out of 58 811 hits) in reco protoDUNE-SP. Do we understand how the code changes in this larg4 pull request can affect the protoDUNE-SP reco products?

Here is the link to the DUNE CI test: https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/8847&platform=Linux%203.10.0-1062.12.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof<url>

**Comment by drivera-fnal** [comment]
Hi,

Yes and no. For cosmics, only the starting trajectory point was being saved even though the old code claimed that we always save the start and the end points no matter what. This change doubled the number of trajectory points for the cosmics which is why there is an increase in memory at 1Gev. The lack of endpoint means that CRT matching was not working properly. This is why I expect the reco products to have changed as well.

I tried to counter the increase in memory by applying a filter that only stores the trajectory points for the primary beam particle and its descendants, leaving out any primary background particles such as halo muons. The ProtoDUNE CI test runs a 1GeV job which doesn’t have very many primary background particles, so the overall effect is an increase in memory from the additional trajectory point stored for all cosmics.

We plan to give a talk on the Tuesday Larsoft Coordination Meeting to discuss what drives the memory usage In the ProtoDUNE refactored simulation.

Best,
David

**Comment by ghost** [comment]
The change of one hit in the reco protoDUNE-SP data products is probably due to a random behavior that, by coincidence, first showed up in the CI build for this pull request, but is unrelated to the code changes. I will take a look at this. 
I will approve this request.

**Comment by ghost** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
