### PR TITLE
Option to store dropped MCParticles as a seperate vector

### PR DESCRIPTION
**Pull request by bear-is-asleep**
Modifies particle list action and larg4 main to store dropped MCParticles. Based on changes made to legacy larg4 - https://github.com/SBNSoftware/larsim/commit/e4bf6060053222f09123f6c5440a19290fb0bdec

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
I have a pending merge of this code and Giusepe's PR - https://github.com/LArSoft/larg4/pull/49, so please check his PR first and I'll be able to merge with the code after that is complete. Thanks!

**Comment by hanswenzel** [comment]
approve

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@bear-is-asleep  https://github.com/LArSoft/larg4/pull/49 has been merged with develop.  Please update this PR as needed.

**Comment by bear-is-asleep** [comment]
> -code-checks Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:
> 
> ```
> format-code \
>   larg4/pluginActions/ParticleListAction.cc
> ```
> 
> Then commit the changes and push them to your PR branch.

The file doesn't change using `cetmodules v3_20_00` 

```
bash-4.2$ format-code \
>   larg4/pluginActions/ParticleListAction.cc
=> Applying clang-format 7.0.0 to 1 files
No files were changed.
```

**Comment by lgarren** [comment]
Thanks @bear-is-asleep

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@bear-is-asleep  Please explain the recent commits.  You appear to have changed this PR, which will send it back for approval.  Also, see the clang format issue...

**Comment by bear-is-asleep** [comment]
> @bear-is-asleep Please explain the recent commits. You appear to have changed this PR, which will send it back for approval. Also, see the clang format issue...

ah sorry, I was attempting to merge into my own develop, not commit changes to this PR. Let me attempt to fix this... sorry about that!

**Comment by lgarren** [comment]
@bear-is-asleep let us know if you have trouble.  We can merge by hand if necessary.

**Comment by bear-is-asleep** [comment]
@lgarren i am having trouble. The last two commits to this branch were merges that shouldn't have occured on this branch, and I'm unsure how to unstage the commits.

**Comment by lgarren** [comment]
> @lgarren i am having trouble. The last two commits to this branch were merges that shouldn't have occured on this branch, and I'm unsure how to unstage the commits.

No problem.  I will merge by hand from the appropriate point in the PR.

**Comment by lgarren** [comment]
approve

Cannot be merged automatically.  We need to merge from before the unintentional updates.

**Comment by lgarren** [comment]
merged by hand at commit   c666b89b654a0d67b78d342f1f346648d19e4942

**Pull request closed without merging**
