### PR TITLE
Handle post step-points with no process-defined steps

### PR DESCRIPTION
**Pull request by knoepfel**
This PR addresses [redmine issue #26221](https://cdcvs.fnal.gov/redmine/issues/26221), where segmentation violations were occurring due to post step-points that have no process-defined step.  The cause for this is not yet understood, but the recommendation from @hanswenzel is to simply handle/side-step these cases.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by absolution1** [comment]
We encountered this bug while testing the refactored LArG4 in the dunefd a couple of days ago.  
Unfortunately I don't think the DUNE CI system (or SBNDs or probably any other CI system) will be adequately testing this fix as most of the CI will be using legacy LArG4.
We'd like to quickly (today) test this fix interactively in dunefd.

**Comment by absolution1** [comment]
The fix works as intended in dune FD.  I've had a brief chat with protodune and it sounds like this probably won't cause an issue for them or their analyses.  Obviously they can weigh in here if it transpires this is not true...

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
