### PR TITLE
add linkage to new nug4_additionalG4Physics lib

### PR DESCRIPTION
**Pull request by nusense**
requires latest nug4 (pull request 1 on NuSoftHEP/nug4)

### CODE REVIEW

**Comment by gartung** [comment]
code-checks

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
@nusense  If you edit this PR to use nug4 v1_10_00, we can try running the CI tests.

**Comment by lgarren** [comment]
@nusense Sorry, it's not going to work.  I took the opportunity to make minor updates to the full nutools suite, so there will be a conflict with the nusimdata version.  My bad.

**Comment by lgarren** [comment]
approve

**Comment by absolution1** [comment]
approve

**Pull request merged**
