### PR TITLE
Restore reporting of unknown PDG in MCTruthEventAction

### PR DESCRIPTION
**Pull request by nusense**
report unknown PDG codes at dtor
quiet down some excessive messages
debug option for reporting skipped and processed codes

### CODE REVIEW

**Comment by nusense** [comment]
This pull request addresses Redmine issue 26210 https://cdcvs.fnal.gov/redmine/issues/26210

**Comment by lgarren** [comment]
code-checks

**Comment by gartung** [comment]
code-checks

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build
(uboone suite is now updated)

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
+1

**Pull request merged**
