### PR TITLE
Select separate volumes for dropped and nominal MCParticles

### PR DESCRIPTION
**Pull request by bear-is-asleep**
Create separate filters for dropped MCParticles and ones that are normally kept (usually primaries). The reason is the number of em shower daughters outside the active volume can grow to be very large and is not used in general, so we should have the option to set the volumes separately. The default is to set the volumes to an empty list, which will cause the module not to produce a separate list of dropped particles at all.

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
The code has been tested for the filter turned off and works with later stages of sbnd reconstruction.

**Comment by lgarren** [comment]
@bear-is-asleep Please bring this PR up to date with the head of develop.  Thanks

**Comment by bear-is-asleep** [comment]
> @bear-is-asleep Please bring this PR up to date with the head of develop. Thanks

updated!

**Comment by lgarren** [comment]
Thanks @bear-is-asleep  Please fix the clang format failure: 

> -code-checks Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:
> 
> ```
> format-code \
>   larg4/Core/larg4Main_module.cc
> ```
> 
> Then commit the changes and push them to your PR branch.

**Comment by absolution1** [comment]
Hey.

How is this review process going?  
I'm happy to provide a review but it looks like @hanswenzel has already been listed as a reviewer.

**Comment by hanswenzel** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
