### PR TITLE
Support multiple larg4 instances

### PR DESCRIPTION
**Pull request by knoepfel**
This PR resolves issue https://cdcvs.fnal.gov/redmine/issues/26249 by allowing the following configuration:

```jsonnet
physics: {
  producers: {
    intime: {
      module_type: larg4Main
      inputCollections: ["intime"]  # sequence of input-tag specifications
    }
    outoftime: {
      module_type: larg4Main
      inputCollections: ["outoftime"] # sequence of input-tag specifications
    }
  }
  g4path: [intime, outoftime]
}
```

This PR requires the `artg4tk:feature/migrate_to_cetmodules` feature branch.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Comment by marcodeltutto** [comment]
Hi @knoepfel, thanks again for this PR. In SBND we tried running using this branch and we found the following:


If we run the `intime` G4 and `outoftime` G4 instances in two *separate* fcls things work as expected. Here, we specify the two different inputs to G4 thanks to the changes you made in this branch.


If we run everything in a single fcl file, for example as you suggested in this PR via

```ruby
physics: {
  producers: {
    intime: {
      module_type: larg4Main
      inputCollections: ["intime"]  # sequence of input-tag specifications
    }
    outoftime: {
      module_type: larg4Main
      inputCollections: ["outoftime"] # sequence of input-tag specifications
    }
  }
  g4path: [intime, outoftime]
}
```

the job fails with error:
```
%MSG-s ArtException:  larg4Main:larg4outtime@Construction  27-Oct-2021 13:39:15 CDT ModuleConstruction
cet::exception caught in art
---- ProductRegistrationFailure BEGIN
  An error occurred during a call to 'produces' or 'reconstitutes'. An attempt was made to declare the following product in the same module:
  Branch type: Event
  Class name: std::vector<artg4tk::PhotonHit>
  Product instance name: LArG4DetectorServicevolOpDetSensitiveXArapucaFilter
---- ProductRegistrationFailure END
%MSG
```

And there are many G4 exceptions of type:

```
Volume volTPCActive has the following list of auxiliary information: 
--> Type: SensDet Value: SimEnergyDeposit

-------- WWWW ------- G4Exception-START -------- WWWW -------

*** ExceptionHandler is not defined ***
*** G4Exception : DET1010
      issued by : G4SDStructure::AddNewDetector()
volTPCActive_SimEnergyDeposit had already been stored in /. Object pointer is overwitten.
It's users' responsibility to delete the old sensitive detector object.
*** This is just a warning message. ***
-------- WWWW ------- G4Exception-END -------- WWWW -------
```

Showing that the old G4 instance was not deleted and it's trying to redeclare all our sensitive detector elements.

**Comment by knoepfel** [comment]
@marcodeltutto, thank you for the report.  I'll take a look in the next week or so.  We decided to merge in this PR anyway because it does not break any currently-functional workflows.

**Comment by marcodeltutto** [comment]
Thanks @knoepfel, having this PR merged is already useful for us

**Pull request merged**
