### PR TITLE
Ensure correct setup/teardown of G4 objects for multiple larg4 modules

### PR DESCRIPTION
**Pull request by knoepfel**
This PR addresses problems found with PR #30.  A long-term solution will be to move some of this behavior into the appropriate service.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by pgreen135** [comment]
@knoepfel you've probably already spotted this, but this seems to have killed all the SimEnergyDeposits for SBND:
```
< G4 | ionandscint | priorSCE | std::vector<sim::SimEnergyDeposit> | 21266
> G4 | ionandscint | priorSCE | std::vector<sim::SimEnergyDeposit> | 0

```
etc.

**Comment by knoepfel** [comment]
> @knoepfel you've probably already spotted this, but this seems to have killed all the SimEnergyDeposits for SBND:
> 
> ```
> < G4 | ionandscint | priorSCE | std::vector<sim::SimEnergyDeposit> | 21266
> > G4 | ionandscint | priorSCE | std::vector<sim::SimEnergyDeposit> | 0
> ```
> 
> etc.

Ugh.  Thanks @pgreen135 for noticing this.

**Comment by knoepfel** [comment]
trigger build

**Comment by knoepfel** [comment]
@pgreen135, I understand what happened--I messed up some of the object ownership when implementing some cleanups.  That's been fixed with the most recent push.  We'll see how the CI tests come back.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
