### PR TITLE
Link custom physics lists in artg4tk

### PR DESCRIPTION
**Pull request by drivera-fnal**
Link artg4tk custom physics lists to make them available in larg4. This should be merged in conjunction with the following artg4tk feature branch : feature/drivera_custom_argon_ncapture , which contains the bulk of the code. This custom physics list (under the name MyQGSP_BERT_ArHP) is registered as an option and can be selected within the PhysicsList service configuration. The custom list was added to acommodate a request from the UC Davis working group in order to base the neutron capture gammas on the latest NNDC data for Ar40. Again, this is optional and does not constitute a breaking change.

### CODE REVIEW

**Comment by lgarren** [comment]
@drivera-fnal  For the sake of our sanity, would you move that title to the description field please?  Thanks!

**Comment by lgarren** [comment]
For future reference, it's a good idea to request a new release of artg4tk explicitly by creating a redmine request.  We will get the new release in place so this PR can be tested.

**Comment by lgarren** [comment]
@drivera-fnal  Would you update this PR to use artg4tk v10_00_03, please?  We are building it now, and would like to run the CI as soon as artg4tk v10_00_03 is installed on larsoft cvmfs.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
CI tests are normal

**Comment by absolution1** [comment]
all looks good to me

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
Was merged by hand into larg4 v09_02_03

**Pull request closed without merging**
