### PR TITLE
make it possible to set the excitation energy in the gdml file

### PR DESCRIPTION
**Pull request by hanswenzel**

### CODE REVIEW

**Comment by hanswenzel** [comment]
approve

**Comment by hanswenzel** [comment]
approve

**Comment by lgarren** [comment]
trigger build

**Review by tomjunk — COMMENTED** [review]
This commit looks fine to me.

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
proper code format done by hand before merge

**Pull request closed without merging**
