### PR TITLE
Fhicl parameter to enable/disable MCParticle trajectory storage by MCTruth process name (follow up of PR#9)

### PR DESCRIPTION
**Pull request by drivera-fnal**

### CODE REVIEW

**Comment by yangtj207** [comment]
trigger build

**Comment by yangtj207** [comment]
We are resolving some issues with dunetpc CI test before proceeding.

**Comment by absolution1** [comment]
approve

**Comment by absolution1** [comment]
Ach, sorry @yangtj207.  I didn't notice that your message had just appeared!

**Comment by yangtj207** [comment]
@lgarren please don't approve this yet. We will do more tests.

**Comment by lgarren** [comment]
I adjusted the labels.  This PR is still pending review and test.  @yangtj207, please let us know when to reopen this for approval.

**Comment by gartung** [comment]
Ah, you also need to delete the comment with approved or +1.

**Comment by yangtj207** [comment]
+1

**Comment by yangtj207** [comment]
@lgarren This PR can be approved now. Thanks.

**Comment by lgarren** [comment]
Thanks @yangtj207.  It will go in next week.  This weeks' release is tagged and building.

**Comment by knoepfel** [comment]
Approve

**Pull request merged**
