### PR TITLE
Changes in ParticleList.cc to run full light simulation

### PR DESCRIPTION
**Pull request by asanchezcastillo**
Particles are now added to the particle list only on their first step. Also add particles to the particle list with energy below the energy cut if it is an optical photon. @hanswenzel could you have a look at this please?

### CODE REVIEW

**Comment by hanswenzel** [comment]
Looks fine please merge

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
