### PR TITLE
Feature/calcuttj second to last

### PR DESCRIPTION
**Pull request by calcuttj**
This includes changes to keep the second to last point during sparsification. 

See:
https://cdcvs.fnal.gov/redmine/issues/25279?issue_count=171&issue_position=1&next_issue_id=25273

### CODE REVIEW

**Comment by lgarren** [comment]
As indicated above, this feature branch requires a new release of nusimdata as specified in redmine issue 25279.  The new release of nusimdata (and the rest of the nutools suite) is not yet ready.

**Comment by lgarren** [comment]
Unfortunately, it is not currently possible to run the CI with a new release of nutools.  I can, however, confirm that all unit tests are fine.

**Comment by knoepfel** [comment]
This should be approved once L2 approval has been granted.

**Comment by absolution1** [comment]
I thought I already approved this one... huh

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
