### PR TITLE
 auxdet that merges steps by particle, change verbosity of the analys…

### PR DESCRIPTION
**Pull request by hanswenzel**
first try with github

auxdet that merges steps by particle, change verbosity of the analys…

### CODE REVIEW

**Comment by gartung** [comment]
code-checks

**Comment by lgarren** [comment]
@hanswenzel  this has gotten a little confused, and we apologize.   The code checks failed.  You must remove the trailing whitespace.  Run removeWhiteSpace.sh (in larsoft) on the following files:
larg4/Analysis/CheckAuxDetHit_module.cc 
larg4/Analysis/CheckMCParticle_module.cc l
arg4/Services/AuxDetSD.cc 
larg4/Services/AuxDetSD.h 
larg4/Services/TempHit.h

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
We did not get the expected report, but checking by hand shows that everything is OK.  @hanswenzel reports that this change has been requested by protodune.

approve

**Comment by lgarren** [comment]
@tomjunk  would you please sign this PR?

**Comment by gartung** [comment]
For future reference 
approve
has to appear on the first line to be registered. My comment and your comment should not trigger anything in their current form.

**Comment by gartung** [comment]
If any Level 1 sends a message with approve on the first line by itself the pull request will automatically be merged.

**Review by tomjunk — APPROVED** [review]
Looks good.  There's a lot of new code I cannot validate just by looking at it, but there does seem to be a real bugfux in AuxDetSD where momentum had been used instead of position.

**Comment by tomjunk** [comment]
approved

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
approved

**Pull request merged**
