### PR TITLE
Added ParticleListActionService configuration parameter to enable trajectory sparsification for MCParticles to reduce memory consumption in the ROOT output stage. If enabled this applies only to particles with full trajectories (as opposed to being called for all particles including those with only a start and and end point)

### PR DESCRIPTION
**Pull request by drivera-fnal**

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests appear to be normal.

**Comment by knoepfel** [comment]
Looks fine to me--L1 approval is granted once L2 is ready.

**Comment by yangtj207** [comment]
+1

**Comment by knoepfel** [comment]
approve

**Pull request merged**
